### ISSUE TITLE
Error on old browsers: Object doesn't support property or method 'gesturable'

### ISSUE THREAD

**Issue by bmarotta** [taye/interact.js#832]
Since migrated from version 1.7.3 to 1.9.19, older browsers throw several errors:

*Object doesn't support property or method 'gesturable'*
Happens only on IE 11
More details: https://sentry.io/share/issue/3eb116113157413aa363ecc9f6ae50de/

*this[i] is not a function*
Happens on old Android mobile (6 and below)
https://sentry.io/share/issue/6303fdd3939b4ff483a66a88abbd6d83/

Rolling back to 1.7.3 makes the error disappear (at least the first one)

### Expected behavior
No error should occur

### Actual behavior
Some browsers throw several errors

### System configuration
**interact.js version**: 1.9.19
**Browser name and version**: IE 11 and other
**Operating System**: Windows 10
