### ISSUE TITLE
Cannot find module '@interactjs/interactjs/index' or its corresponding type declarations.

### ISSUE THREAD

**Issue by robertrachita** [taye/interact.js#1050]
In a TypeScript project, when trying to compile, i get the following error:

> index.d.ts(2,22): error TS2307: Cannot find module '@interactjs/interactjs/index' or its corresponding type declarations.

**System configuration**
interactjs version: 1.10.27
operating system: debian 11
npm version: 10.7.0
node: 18.20.4
typescript: 4.9.5

**Comment by fivaz3** [comment]
at least post your tsconfig.json. each typescript project operates differently based on the tsconfig.json

**Comment by robertrachita** [comment]
``` "compilerOptions": { 
		"newLine": "LF",
		"noImplicitAny": true,
		"noImplicitThis": true,
		"strict": true,
		"strictNullChecks": false,
		"target": "ES2022",
		"module": "ES2022",
		"outDir": "./build",
		"declaration": false,
		"baseUrl": ".",
		"paths": {
			"project-name/*":["ts/src/*"]
		},
		"types": [
			"d3",
			"dropzone",
			"jquery",
			"jquery.cookie",
			"jqueryui",
			"jstree",
			"ol",
			"easymde",
		]
	},
	"include": [
		"./ts/src/**/*.ts",
		"./module/**/*.ts"
	],
}

```

In my project, this is the only package that throws any errors simply by being installed and imported into a file.

**Comment by athira-inapp** [comment]
Did you find fix for this issue? I also have same issue, when i migrate my angular version from 8 to 19.1.
