### ISSUE TITLE
Uncaught TypeError: interact is not a function 

### ISSUE THREAD

**Issue by kheber92** [taye/interact.js#895]
Since today, interactjs 'suddenly' stopped working on **version 1.10.9**. 
I used it until yesterday without any problems, today I always get the error described below.

### Error message
`Uncaught TypeError: interact is not a function`

Safari browser shows an a bit more detailed error message:
`TypeError: interact is not a function. (In 'interact('.draggable')', 'interact' is an instance of Object) `

### Minimal setup at codepen
[https://codepen.io/keber/pen/ExZNMZv](url)
If you open the console, you can see the error message.

### System configuration
I tested both available scripts suggested in the installation guide, both come with the same error.
https://cdn.jsdelivr.net/npm/interactjs/dist/interact.min.js
https://unpkg.com/interactjs/dist/interact.min.js
Both are currently **version 1.10.9**.
Tested on Chrome, Firefox, Safari.

### Workaround
Using **version 1.10.8**.

What also seems to be working is importing the package as CDN streamlined (https://interactjs.io/docs/installation/#cdn-streamlined). Although the pre-bundled should work as well I think.

**Comment by taye** [comment]
Should be fixed in `v1.10.10`
