### ISSUE TITLE
Invalid types when integrating in angular

### ISSUE THREAD

**Issue by tiberiuzuld** [taye/interact.js#891]
Compiling the library with typescript for angular framework generates VUE types errors.
It was working in v1.10.3

### Expected behavior
Should complain about vue types when compiling the library for angular

### Actual behavior
```ts

Error: node_modules/@interactjs/types/index.d.ts:3941:53 - error TS2307: Cannot find module '@vue/r
eactivity' or its corresponding type declarations.

3941     export { toRefs, computed, reactive, ref } from '@vue/reactivity';
                                                         ~~~~~~~~~~~~~~~~~


Error: node_modules/@interactjs/types/index.d.ts:3942:31 - error TS2307: Cannot find module '@vue/r
untime-dom' or its corresponding type declarations.

3942     export { onMounted } from '@vue/runtime-dom';
                                   ~~~~~~~~~~~~~~~~~~


Error: node_modules/@interactjs/types/index.d.ts:3943:50 - error TS2307: Cannot find module '@vue/r
untime-core' or its corresponding type declarations.

3943     export { createVNode, createTextVNode } from '@vue/runtime-core';
                                                      ~~~~~~~~~~~~~~~~~~~

```

### System configuration
**interact.js version**: 1.10.6 , 1.10.5 , 1.10.4
**Browser name and version**: Any
**Operating System**: Any

typescript 4.1.5
node 14.15.1
npm 6.14.11

**Comment by taye** [comment]
Fixed in `v1.10.8`
